### ISSUE TITLE
프로젝트 실행 관련 질문드립니다.

### ISSUE THREAD

**Issue by parkhojun** [roharon/gmoney-store-web#4]
좋은 프로젝트를 업로드 해주셔서 감사합니다.
프로젝트를 보고 yarn start를 해 보았지만 접속이 되지 않았습니다.
코드를 직접 로컬에서 실행해보고 싶습니다.
해당 프로젝트를 어떻게 하면 실행시킬 수 있는지(how to run) 알려주시면 감사하겠습니다!

**Comment by roharon** [comment]
해당 프로젝트에 관심 가져주셔서 감사합니다

현재 master 브랜치 기준으로 
```bash
yarn install
yarn start
```
를 통해서 로컬에서 실행이 가능합니다 :)

+추가
혹은 docker를 이용해서
```
docker build .
docker run -it --rm -p 80:80 gmoney-web_web
```
로 바로 실행할 수 있습니다
